
[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[cursor.style]
shape = "Block"

[font]
size = 16

[font.bold]
family = "Hasklug Nerd Font"

[font.bold_italic]
family = "Hasklug Nerd Font"

[font.italic]
family = "Hasklug Nerd Font"

[font.normal]
family = "Hasklug Nerd Font"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "F"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B0"
key = "Key0"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B1"
key = "Key1"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B2"
key = "Key2"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B3"
key = "Key3"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B4"
key = "Key4"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B5"
key = "Key5"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B6"
key = "Key6"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B7"
key = "Key7"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B8"
key = "Key8"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B9"
key = "Key9"
mods = "Alt"

[scrolling]
history = 10000

[terminal.shell]
args = ["-l", "-c", "[[ ! -z $(tmux list-clients) ]] && tmux || tmux attach || tmux"]
program = "/bin/zsh"

[window]
decorations = "buttonless"
dynamic_padding = true
dynamic_title = true
opacity = 0.95

[window.padding]
x = 10
y = 10

[general]
import = ["/Users/miaxyhunt/.config/alacritty/themes/themes/gruvbox_material_medium_dark.yaml"]

[terminal]
